version: "3.8"
services:

  nginx:
    image: nginx:1.21.1-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx1:/etc/nginx

  vaultwarden:
    image: vaultwarden/server:latest
    volumes:
      - ./data/vaultwarden:/data
