version: '3.8'

networks:
  net_home:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.99.0/24 

services:

  nginx:
    image: nginx:1.21.1-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/nginx:/etc/nginx/conf.d
    networks: 
      - net_home

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - net_home

  bitwarden:
    image: vaultwarden/server:latest
    volumes:
      - ./vw-data/:/data/
    networks:
      - net_home
