version: "3.8"
services:
    
  kodi:
    image: "linuxserver/kodi-headless"

    volumes:
      - ./data:/config/.kodi
    environment:
      PGID: gid 
      PUID: uid 
      TZ: Europe/Moscow 
    ports:
      - "8080:8080"
      - "9090:9090"
      - "9777:9777/udp" 
