version: '3.8'

services:

  bitwarden: 
    container_name: bitwarden
    image: vaultwarden/server:latest 
    restart: unless-stopped
    volumes: 
      - bitwarden:/data 
    environment: 
      - VIRTUAL_HOST=bw.itdog.ru 
      - VIRTUAL_PORT=80 
      - LETSENCRYPT_HOST=bw.itdog.ru 
      - LETSENCRYPT_EMAIL=hwts@mail.ru 

networks:
  default:
    external: true
    name: net1

volumes:
  bitwarden:
