version: "3.8"
services:

  vaultwarden:
    image: vaultwarden/server:latest
    ports:
      - "81:80"
    volumes:
      - ./ssl/keys/:/ssl/
      - ./vw-data/:/data/
        #    restart: always
      #environment:
      #      ROCKET_TLS: '{certs="/ssl/bitwarden.pem",key="/ssl/bitwarden.key"}'
