version: '3.8'

services:

  gitlab:
    container_name: gitlab
    image: 'gitlab/gitlab-ee:latest'
    restart: unless-stopped
    hostname: 'git.itdog.ru'
    ports:
      - "16499:22"
    environment:
      VIRTUAL_HOST: git.itdog.ru
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: git.itdog.ru
      LETSENCRYPT_EMAIL: hwts@mail.ru
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://git.itdog.ru'
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
 
volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:

networks:
  default:
    name: net1
