version: '3.8'

services: 
 
  nginx-proxy: 
    container_name: nginx-proxy
    image: jwilder/nginx-proxy 
    restart: unless-stopped
    ports: 
      - "80:80" 
      - "443:443" 
    volumes: 
      - nginx_certs:/etc/nginx/certs 
      - nginx_vhost:/etc/nginx/vhost.d  
      - nginx_html:/usr/share/nginx/html    
      - /var/run/docker.sock:/tmp/docker.sock:ro 

  nginx-proxy-letsencrypt: 
    container_name: nginx-proxy-letsencrypt 
    image: jrcs/letsencrypt-nginx-proxy-companion 
    restart: unless-stopped
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro 
    volumes_from: 
      -  nginx-proxy     
    environment: 
      - DEFAULT_EMAIL=hwts@mail.ru 
    depends_on:
      - nginx-proxy

networks:
  default:
    external: true
    name: net1

volumes:
  nginx_certs:
  nginx_vhost:
  nginx_html:
