version: '3.8'

services:

  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wg
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - SERVERURL=wg.itdog.ru # Домен или внешний айпишник
      - SERVERPORT=51820 # Порт для подключения
      - PEERS=hwts-phone,hwts-pc #Создание пиров(клиентов)
      - PEERDNS=auto 
      - INTERNAL_SUBNET=10.13.13.0 # Внутренняя шз адресация
      - ALLOWEDIPS=0.0.0.0/0 # Разрешенные сети (0.0.0.0/0 - разрешить маршрут по умолчанию)
    volumes:
      - ./data/appdata/config:/config
      - ./data/lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
